trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: ${{ replace(variables['System.PullRequest.SourceBranch'], '/', '-') }}
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: ${{ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') }}

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x
      echo "------- SourceBranch"
      echo $(Build.SourceBranch)
      echo "------- direct branch name"
      echo ${{ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') }}
      echo "------- pr branch name"
      echo $(System.PullRequest.SourceBranch)
      echo "------- custom"
      echo ${{variables.branchName}}
      echo "------- env"
      env
