trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    branchName: ${{ replace(variables['System.PullRequest.SourceBranch'], '/', '-') }}
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    branchName: ${{ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') }}

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x
      echo '##vso[task.setvariable variable=branchName]$(echo "$(System.PullRequest.SourceBranch)" | sed "s/\//-/g")'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      set -x
      echo "------- SourceBranch"
      echo $(Build.SourceBranch)
      echo "------- SourceBranch short"
      echo ${{ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') }}
      echo "------- PullRequest SourceBranch"
      echo $(System.PullRequest.SourceBranch)
      echo "------- PullRequest SourceBranch short"
      echo ${{ replace(variables['System.PullRequest.SourceBranch'], 'test', 'ssss') }}
      echo "------- PullRequest SourceBranch custom"
      echo $(echo "$(System.PullRequest.SourceBranch)" | sed "s/\//-/g")
      echo "------- custom"
      echo $(branchName)
      echo "------- env"
      env
