trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo ${{ replace(variables['Build.SourceBranchName'], 'refs/heads/', '') }}
      echo $(System.PullRequest.SourceBranch)
